### ISSUE TITLE
new repo for nodejs-polars

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/nodejs-polars#1]
@universalmind303 could you push the code to this new repo. You may also do a git filter branch to keep only the node-js related code in the history?

**Comment by universalmind303** [comment]
@ritchie46 can you add me as an owner to this repo?

**Comment by ritchie46** [comment]
You should be invited as maintainer.  Did you receive that mail? If not I can try it again.

**Comment by universalmind303** [comment]
ahh, spam filters blocked it for some reason. all set now. Thanks!!
