### ISSUE TITLE
`pl.readJSON()`  parse new line `\n` wrongly.

### ISSUE THREAD

**Issue by kingrongH** [pola-rs/nodejs-polars#101]
#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

`0.8.1`

#### What operating system are you using polars on?

macOS 13.4  intel

#### What node version are you using

node 18.16.0 

#### Describe your bug.

`pl.readJSON()`  parse new line `\n` wrongly.

`\n` => `\\` 

#### What are the steps to reproduce the behavior?

`test.json` file
```json
[
  {
    "key": "\n所"
  }
]
```

**Example**
index.js

```js
const pl = require('nodejs-polars'); 

const df = pl.readJSON("./test.json");
console.log(df.select(pl.col("*")).toRecords());
```

#### What is the actual behavior?

`node index.js`  output

```
[ { key: '\\n�' } ]
```

#### What is the expected behavior?

```
[ { key: '\n所' } ]
```

**Comment by Bidek56** [comment]
This is a rough one, b/c:
1. it works fine in my dev env, I get: `[ { key: '\n所' } ]` but when I use your example using node and 0.8.1 release I get the same error as you
2. It does not work in Python/Polars, due to `UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 37-38: invalid continuation byte`

**Comment by Bidek56** [comment]
This issue is related to [#10034](https://github.com/pola-rs/polars/issues/10034) which would be downstream for this library.

**Comment by daolanfler** [comment]
flowing code copied from [doc](https://pola-rs.github.io/nodejs-polars/functions/pl.readJSONStream.html) also doesn't work 
```ts
import pl from "nodejs-polars";
import { Stream } from "stream";

const readStream = new Stream.Readable({ read() {
  //
} });
readStream.push(`${JSON.stringify({ a: 1, b: 2 })} \n`);
readStream.push(`${JSON.stringify({ a: 2, b: 2 })} \n`);
readStream.push(`${JSON.stringify({ a: 3, b: 2 })} \n`);
readStream.push(`${JSON.stringify({ a: 4, b: 2 })} \n`);
readStream.push(null);

pl.readJSONStream(readStream).then((df) => console.log(df));
```

<details>
<summary>Error logs</summary>

/home/qi/tmp/mytest-package/node_modules/.pnpm/registry.npmmirror.com+nodejs-polars@0.8.0/node_modules/nodejs-polars/bin/io.js:296
                const df = (0, dataframe_1._DataFrame)(polars_internal_1.default.readJson(chunk, options));
                                                                                 ^


Error: Not yet implemented: read an Array from a non-Array JSON
    at LineBatcher.<anonymous> (/home/qi/tmp/mytest-package/node_modules/.pnpm/registry.npmmirror.com+nodejs-polars@0.8.0/node_modules/nodejs-polars/bin/io.js:296:82)
    at LineBatcher.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at LineBatcher._flush (/home/qi/tmp/mytest-package/node_modules/.pnpm/registry.npmmirror.com+nodejs-polars@0.8.0/node_modules/nodejs-polars/bin/io.js:76:14)
    at LineBatcher.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:707:12)
    at prefinish (node:internal/streams/writable:719:7)
    at finishMaybe (node:internal/streams/writable:729:5) {
  code: 'GenericFailure'
}

Node.js v20.5.1

</details>

if the `readStream` only pushes one line then it's ok.  not sure if it's related to this issue

**Comment by Bidek56** [comment]
This is most likely a bug and the [test](https://github.com/pola-rs/nodejs-polars/blob/5f2ada03d6b7028b6b3b72855d77744578e73a90/__tests__/io.test.ts#L353) is is failing for the wrong reason.
@universalmind303 Would you know what is happening in [this](https://github.com/pola-rs/nodejs-polars/blob/5f2ada03d6b7028b6b3b72855d77744578e73a90/polars/io.ts#L74) code? Thx

**Comment by Bidek56** [comment]
@daolanfler Thanks for finding this issue.
