### ISSUE TITLE
feat: polars + bun js runtime

### ISSUE THREAD

**Issue by ryanrussell** [pola-rs/nodejs-polars#110]
The new [zig-based runtime for JS](https://github.com/oven-sh/bun) looks extremely promising:

Specifically, FFI appears much more performant: https://github.com/oven-sh/bun#bunffi-foreign-functions-interface

@ritchie46 @universalmind303  -- has this made your radar yet? 

I was considering giving it a run on my side; but figured it made sense to ask you guys first. 

If this is of interest, do you have any guidance on how you would like to see it in the project structurally?

Best,
Ryan

**Comment by stinodego** [comment]
Moving this to the `nodejs-polars` repo. Not sure if it is still relevant.

**Comment by ryanrussell** [comment]
@stinodego 

As much as I'd love to help on this, I do not foresee having the bandwidth in the near future. 

Feel free to close for housekeeping unless someone else has the cycles. It can always be recreated if someone steps forward to take it on.

**Comment by stinodego** [comment]
All right, I'll close this for now. Thank you!
