### ISSUE TITLE
add support for streaming inputs/outputs

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/nodejs-polars#114]
#### Describe your feature request
rust & python both support OOC processing via `sink_X` and `collect({streaming: true})`. We should add support for those as well.

**Comment by 55ii** [comment]
Will this give the nodejs-polars functionality to be able to read_parquet_cloud & write_parquet_cloud with the out of core streaming functionality on large S3 datasets?

Looks like rust and python are now having/getting native cloud support for scan_parquet and optimizations for cloud.

**Comment by Bidek56** [comment]
@universalmind303 Since we have `sinkCSV and `sinkParquet` implemented, is it time to close this ticket? Thx
