### ISSUE TITLE
CSV reader is not properly handling separators inside double quotes

### ISSUE THREAD

**Issue by Danksa** [pola-rs/nodejs-polars#116]
#### Have you tried latest version of polars?

- [yes] ✓
- [no]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.8.2

#### What operating system are you using polars on?

Ubuntu 22.04.2 LTS

#### What node version are you using

v20.3.1

#### Describe your bug.

When trying to read a CSV file via readCSV (same happening with readCSVStream) containing data of the following form:

a,b,c,d
1,test,"a,b,c",another test

It ignores the double quotes and reads a DataFrame with the following content:

| a | b    | c       | d |
|---|------|---------|---|
| 1 | test | "a,b,c" | b |

#### What are the steps to reproduce the behavior?

```typescript
const body = Buffer.from('a,b,c,d\n1,test,"a,b,c",another test');

const dataFrame = readCSV(body, {
    quotChar: '"',

    inferSchemaLength: 0
})

dataFrame.writeParquet("test.parquet");
```

Result when looking at it using a parquet viewer:
![Output](https://i.imgur.com/00dc1KE.png)

#### What is the expected behavior?

I would instead expect a DataFrame with the following content:
| a | b    | c       | d |
|---|------|---------|---|
| 1 | test | "a,b,c" | b |

**Comment by Bidek56** [comment]
Have you tried this example in Python Polars? Nodejs-polars uses Rust libraries hence this maybe an upstream issue.

**Comment by Bidek56** [comment]
@dotMortis I have a PR for it. Thanks for catching this 🐞

**Comment by Danksa** [comment]
@Bidek56 Wow, thanks for the quick response! Just passing "quoteChar" in the current version works like a charm 👍
