### ISSUE TITLE
import of polars fails

### ISSUE THREAD

**Issue by kuatroka** [pola-rs/nodejs-polars#119]
#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

0.8.2

#### What operating system are you using polars on?

Mac OS Ventura

#### What node version are you using
18.16.0

#### Describe your bug.

After `npm install node-polars` and importing it in my Sveltekit app as `import pl from 'nodejs-polars';` I'm getting an error
```
✘ [ERROR] No loader is configured for ".node" files: ../../node_modules/nodejs-polars-darwin-arm64/nodejs-polars.darwin-arm64.node

    ../../node_modules/nodejs-polars/bin/native-polars.js:130:48:
      130 │                         nativeBinding = require('nodejs-polars-darwin-arm64');
          ╵                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

4:41:40 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
../../node_modules/nodejs-polars/bin/native-polars.js:130:48: ERROR: No loader is configured for ".node" files: ../../node_modules/nodejs-polars-darwin-arm64/nodejs-polars.darwin-arm64.node
    at failureErrorWithLog (/Users/yo_macbook/Documents/dev/evidence-standard-20230912/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/yo_macbook/Documents/dev/evidence-standard-20230912/node_modules/esbuild/lib/main.js:1048:25
    at /Users/yo_macbook/Documents/dev/evidence-standard-20230912/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```
    
It mentions 'node-loader' so Installed it too, but it didn't help

#### What is the expected behavior?

What do you think polars should have done?
It should have been imported with no errors so I can continue with the rest of the code examples and build actual dataframes. Thanks

**Comment by Bidek56** [comment]
1. I think question belongs to SO, not GH
2. Please produce MRE
3. I believe Sveltekit is a frontend library, `node-polars` only works in the server
4. If you are using `node-polars` on the backend, you may want to try [vite-node](https://github.com/vitest-dev/vitest/tree/main/packages/vite-node)

**Comment by kuatroka** [comment]
Thanks, Sveltekit is a backend too. 
I just assumed that it'd be the same way as in using duckdb node module. Just install it with npm and import into a page. 

I'll have to look further into it then. Thanks

**Comment by Bidek56** [comment]
If you need help pls post on SO or Discord, otherwise pls close this ticket. Thx
