### ISSUE TITLE
.rename() and .alias()

### ISSUE THREAD

**Issue by Nekobaex** [pola-rs/nodejs-polars#121]
#### Describe your feature request

Hello, I have noticed that in the nodejs-polars library, 
the `.rename()` function can be called by `Series`, `DataFrame`, 
while the `.alias()` function can be called by `Series`, `Expr`. 
These two functions serve the same purpose, 
but I was wondering if it would be possible to make one of them applicable to all three types: `Series`, `DataFrame`, and `Expr`.

Thank you!

**Comment by Bidek56** [comment]
@Nekobaex `nodejs-polars` keeps functionality on par with Python Polars
 I believe `.rename()` and `.alias()` functionality is the same as in Python Polars

It makes sense, since `df.select(pl.col("foo"))` results in an expression which then can be aliased.
