### ISSUE TITLE
Activating pl.Config.activate_decimals() in nodejs-polars

### ISSUE THREAD

**Issue by 55ii** [pola-rs/nodejs-polars#122]
#### Describe your feature request

I encountered an `Error: Not yet implemented: Deserializing type Decimal(6, 2) from parquet `
when reading a external sys created parquet file with readParquet.

When going through the rust polars library. I have seen this issue answering a solution https://github.com/pola-rs/polars/issues/8191

It looks like config setting with pl.Config.activate_decimals() in https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.Config.activate_decimals.html#polars.Config.activate_decimals
sets the temporary setting for decimal type.

Can we also have this setting available in nodejs-polars.

Thanks

**Comment by Bidek56** [comment]
Following this [example](https://github.com/pola-rs/polars/issues/8191) I am able to write a Parquet file with decimal when using `pl.Config.activate_decimals()`
Then I am able to read the sample Parquet file created above just fine using this TS code:

```
import { pl } from "nodejs-polars"
const df = pl.readParquet("decimal_test.parquet")
```

Would you have MRE to reproduce your error above? Thx
