### ISSUE TITLE
Add ewm

### ISSUE THREAD

**Issue by sergeysolovev** [pola-rs/nodejs-polars#126]
Would be amazing to see exponential weighted momentum functions in this library: mean, std.

https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.ewm_mean.html

**Comment by Bidek56** [comment]
@universalmind303 would you know how to expose `polars_core::series::ops::ewm::{ ewm_mean, ewm_std, ewm_var };` to this project? Thx

**Comment by universalmind303** [comment]
@Bidek56 we should follow what py_polars does & use the expression api for both series & expr.  We are already doing this for many series ops, such as `clip` and `shiftAndFill`.

**Comment by Bidek56** [comment]
[ewm_mean](https://github.com/pola-rs/nodejs-polars/blob/038312f9f8aabfc2629f4937792b161643d078e5/src/lazy/dsl.rs#L1325) is already implemented for JsExp, just needs to be exposed, but I am trying to implement `ewm_mean` for series
