### ISSUE TITLE
Node Webpack "Module not found" error

### ISSUE THREAD

**Issue by caerbannogwhite** [pola-rs/nodejs-polars#13]
#### Have you tried latest version of polars?

- [yes]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

nodejs-polars version 0.6.0

#### What operating system are you using polars on?

Windows 11

#### What node version are you using

node v16.16.0

#### Describe your bug.

The compilation with npm produces the following log
[log.txt](https://github.com/pola-rs/nodejs-polars/files/9749319/log.txt)

#### What are the steps to reproduce the behavior?

Install polars with `npm i -s nodejs-polars` in a project with webpack and run it.

#### What is the actual behavior?

The actual behaviour is reported in the log.

#### What is the expected behavior?

The compilation runs smoothly.

**Comment by Bidek56** [comment]
@caerbannogwhite Is this still an issue? Thx

**Comment by verikono** [comment]
https://github.com/verikono/pola-rs-node-issue-13

This repo recreates this issue. The issue remains on v0.8.0

**Comment by Bidek56** [comment]
Please use [node-loader](https://github.com/webpack-contrib/node-loader), it fixes this issue.

**Comment by verikono** [comment]
https://github.com/verikono/pola-rs-node-issue-13/commit/f0c2990d5e629e3a2111ec9e3332e07b426a621d

works for me.

**Comment by Bidek56** [comment]
@caerbannogwhite Please try [node-loader](https://github.com/webpack-contrib/node-loader), if it fixes this issue, please close this ticket. Thx

**Comment by verikono** [comment]
I've cloned the pola-rs book project and will add a section for bundler
usage.

**Comment by universalmind303** [comment]
I think it could be added to the node-polars specific docs. https://pola-rs.github.io/nodejs-polars/

**Comment by verikono** [comment]
Lets do both! :)
