### ISSUE TITLE
When will get new version. It seems the build step is getting failed.

### ISSUE THREAD

**Issue by sukeshpabolu** [pola-rs/nodejs-polars#133]
It has been more than a month that the library is updated. Please check regarding the build step

**Comment by Bidek56** [comment]
@sukeshpabolu We could do a minor release, but it's up to @universalmind303 
We are waiting for the next RS 0.34 release, then we can do a bigger release.
Thanks for your patience.

**Comment by Bidek56** [comment]
@sukeshpabolu `Please check regarding the build step` Can you please elaborate on this? Thx
