### ISSUE TITLE
Can node-js polars be used in the browser?

### ISSUE THREAD

**Issue by paddymul** [pola-rs/nodejs-polars#136]
I have a frontend only project, in typescript, built by webpack/tsc.  
Is it reasonable to include nodeJS-Polars as a dependency?
Does this work via web assembly?
If this is a reasonable path, what is the built module size?

Sorry if the answer should be obvious.  I suspect that this isn't an intended usecase because of all of the platform specific compliation issues that I have seen on the repo. Maybe you could update the README with a note based on this question.

**Comment by universalmind303** [comment]
nodejs-polars is incompatible with frontend applications. 

There have been some attempts at building a frontend compatible library https://github.com/pola-rs/js-polars, but WASM support in rust is quite nascent.

**Comment by Bidek56** [comment]
Readme has been updated in #135
