### ISSUE TITLE
Print full DataFrame object data in console

### ISSUE THREAD

**Issue by Dennis-Nedry-From-Jurassic-Park** [pola-rs/nodejs-polars#14]
Hello. How to print full DataFrame object data in console ?

```ts
import pl from 'nodejs-polars';
import * as util from "util";

let df: pl.DataFrame;

df = pl.DataFrame({
    "row": [
        "A", "B", "C", "D", "E", "F",
        "A2", "B2", "C2", "D2", "E2", "F2",
        "G", "H", "J", "K", "L", "M"
    ],
   });

console.log(util.inspect(df, true, null, true))
```

ts-node -r tsconfig-paths/register apps/ms-analytics/src/df.ts

Result:

![2022-10-11_102551](https://user-images.githubusercontent.com/29069587/195023670-9bd5dc67-5f32-4348-9a36-83fb2f4ec9d2.png)

**Comment by universalmind303** [comment]
you can use the Config object to increase the number of rows printed

```js
import pl from 'nodejs-polars'
pl.Config().setTblRows(SOME_HUGE_NUMBER)

const df = getDFSomehow();

console.log(df)
```

Alternatively, If performance is a non issue, you can collect the dataframe to records & console log it as normal JS objects.

```js
const df = getDFSomehow()
console.log(df.toRecords())
```
