### ISSUE TITLE
scanCSV method skip more lines that it should with certain options

### ISSUE THREAD

**Issue by Interlude-code** [pola-rs/nodejs-polars#146]
#### What version of polars are you using?

0.8.3"

#### What operating system are you using polars on?

linux

#### What node version are you using
node 20.0 

#### Describe your bug.

when calling method scanCSV with hasHeader set to false, and skipRows equals 1 the resulting dataframe skips one more rows than it should, resulting with a dataframe, if skipRows equals 2 the resulting dataframe skips two more rows than it should and so on

#### What are the steps to reproduce the behavior?

create a csv file with a couple lines, then create a dataframe with the following configuration:

```
pl.scanCSV( path , {
                      skipRows: 1,
                      hasHeader: false,
                  inferSchemaLength: 0,
              })
```

and notice the amount of rows of the dataframe vs the amount of rows of the csv file, then increase the value of skipRows and compare

**Comment by Bidek56** [comment]
This example works fine in the un-released (dev) version of the code. 
Unfortunately we had not had a release for a while, hence you are seeing this issue.
