### ISSUE TITLE
InferSchemaLenght  it does not work

### ISSUE THREAD

**Issue by Interlude-code** [pola-rs/nodejs-polars#153]
#### What version of polars are you using?

0.8.4

#### What operating system are you using polars on?

ubuntu 22.04

#### What node version are you using
node 20

#### Describe your bug.

IngerSchemaLenght bug

let df = readCsv(buffer, { 
skipRows: 1,
hasHeaders: false,
InferSchemaLength : 0
}) 

Before in the porlars version 0.8.3 when the InferSchemaLength option was uploaded
The dataframe was created with all columns in string but now after updating the dataframes always infer the types which causes me problems due to loss of some data

**Comment by Bidek56** [comment]
#156 has a fix for this issue. Sorry the trouble and thx for binging this up.

**Comment by Bidek56** [comment]
Can you please check: "nodejs-polars": "0.9.0"? Thx
