### ISSUE TITLE
filtering by equals doesn't work

### ISSUE THREAD

**Issue by sigmaSd** [pola-rs/nodejs-polars#158]
#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

0.8.4

#### What operating system are you using polars on?

linux

#### What node version are you using
Node.js v20.10.0

#### Describe your bug.
filtering by equals doesn't work

#### What are the steps to reproduce the behavior?

code
```js
const pl = require("nodejs-polars");

df = pl.DataFrame({
  "foo": [1, 2, 3],
  "bar": [6, 7, 8],
  "ham": ["a", "b", "c"],
});

df.filter(
  pl.col("foo").eq("a"), //neq also fails,maybe others as well, (gt and lt works)
);
```
fails with `Error: not found: unable to find column "a"; valid columns: ["foo", "bar", "ham"]`

**Comment by Bidek56** [comment]
You syntax is not correct. It should be: `const res= df.filter(pl.col("ham").eq(pl.lit("a")));`

**Comment by sigmaSd** [comment]
thanks works indeed, I followed the code from the reference here https://pola-rs.github.io/nodejs-polars/interfaces/pl.DataFrame-1.html#filter

**Comment by Bidek56** [comment]
Thanks for pointing this out, I have a #159  to fix this doc issue.
Interesting `df.filter(pl.col("foo").eq(3))` works fine for a numeric col but not for string.
This would be a question for the core Polars team. If interested, please ask on Discord.
