### ISSUE TITLE
Fail to install on macOS ARM64

### ISSUE THREAD

**Issue by tisonkun** [pola-rs/nodejs-polars#16]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://www.npmjs.com/package/nodejs-polars) of Polars.

### Issue description

```
$ yarn add nodejs-polars

➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: nodejs-polars-android-arm64@npm:0.6.0: No candidates found
    at ce (/Users/chenzili/.cache/node/corepack/yarn/3.2.2/yarn.js:439:7864)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async go (/Users/chenzili/.cache/node/corepack/yarn/3.2.2/yarn.js:390:10446)
➤ YN0000: └ Completed in 1s 159ms
➤ YN0000: Failed with errors in 1s 161ms
```

### Reproducible example

```javascript
yarn add nodejs-polars
```

### Expected behavior

Successfully install.

**Comment by universalmind303** [comment]
@Ahrcantos can you try with the latest version of nodejs-polars `0.7.1`

**Comment by Ahrcantos** [comment]
@universalmind303 Installation with `yarn` works perfectly on version `0.7.1` for me. Thank you.

**Comment by tisonkun** [comment]
I'm trying it now.

**Comment by tisonkun** [comment]
Successfully install 0.7.2.

Closed as resolved.

**Comment by tisonkun** [comment]
@universalmind303 One question here: can this package be used in browser? Or it requires a node runtime?

**Comment by universalmind303** [comment]
Currently it can only be used in node. Browser support is much trickier as it has to be compiled to wasm.  I've been doing some work on a browser implementation, but it is far from ready.
