### ISSUE TITLE
DataFrame - `schema_overrides` param is missing

### ISSUE THREAD

**Issue by tvavrys** [pola-rs/nodejs-polars#170]
#### Describe your feature request

Title says it all. `schema_overrides` param is missing

See https://docs.pola.rs/py-polars/html/reference/dataframe/index.html#dataframe

> Support type specification or override of one or more columns; note that any dtypes inferred from the schema param will be overridden.

Current Code Reference: https://github.com/pola-rs/nodejs-polars/blob/main/polars/dataframe.ts#L2533

**Comment by Bidek56** [comment]
We support `schema` when creating a DF using `pl.DataFrame(...)`
How different would `schema_overrides` be from `schema` or `dtypes`?

**Comment by tvavrys** [comment]
That's a great question. It doesn't work. It uses interference no matter what you choose in schema. Then I noticed the `schema_overrides` in Python/Rust documentation.

**Comment by Bidek56** [comment]
Do you have a MRE? Our tests pass, hence maybe you have a different example. Thx

**Comment by Bidek56** [comment]
Looking at the [code](https://github.com/pola-rs/nodejs-polars/blob/83e54144b7f3b6d56e0b4635167dc8bf8af8614e/polars/dataframe.ts#L2545), it only respects options in this case:

```
const rows = [{ a: 1, b: 2, c: null }];

const df = pl.DataFrame(rows, {
  schema: { a: pl.Int32, b: pl.Int32, c: pl.Utf8 },
  orient: "row",
});
```
