### ISSUE TITLE
Pivot not working as expected

### ISSUE THREAD

**Issue by SailingZhou** [pola-rs/nodejs-polars#172]
#### What version of polars are you using?

0.8.4

#### What operating system are you using polars on?
Mac

#### What node version are you using
16.15.1

#### Describe your bug.

node polars's dataFrame pivot is not working as expected. Python version had the same bug but it's fixed in latest 20+ version.
https://github.com/pola-rs/polars/issues/12407

#### What are the steps to reproduce the behavior?

```
df = pl.DataFrame({'a':['beep', 'bop'],'b':['a','b'],'c':['s','f'],'d':[7,8], 'e':['x', 'y']})
df.pivot(values=['a'], index='b', columns=['c', 'e'], aggregate_function='count')
```

#### What is the actual behavior?

shape (2, 5) 
| b   | s    | f    | x   | y   |
|-----|------|------|-----|-----|
| str | u32  | u32  | u32 | u32 |
| "a" | 1    | null | 1   | null|
| "b" | null | 1    | null| 1   |

#### What is the expected behavior?
| b   | s_x | f _y |
|-----|-----|-------|
| str | u32 | u32   |
| "a" | 1   | null  |
| "b" | null| 1     |

What do you think polars should have done?
Sync with the python implementation

**Comment by Bidek56** [comment]
@SailingZhou If this bug existed in Python Polars, it will probably gets fixed when we move nodejs to rs 0.37.
Thanks for pointing this out.

**Comment by SailingZhou** [comment]
Hey @Bidek56, thank you for the respond!  Do we know when will we move move nodejs to rs 0.37 ?

**Comment by Bidek56** [comment]
I don't know wheo, we still haven't released rs 0.36, hence it may be a while. Sorry.

**Comment by Bidek56** [comment]
Using `"nodejs-polars": "0.9.0"` with:
```
import pl from "nodejs-polars"
const df = pl.DataFrame({'a':['beep', 'bop'],'b':['a','b'],'c':['s','f'],'d':[7,8], 'e':['x', 'y']});
const pvdf = df.pivot("a", { index: 'b', columns: ['c','e'], aggregateFunc: 'count'});
console.log(pvdf);
```
I see:

```
shape: (2, 3)
┌─────┬───────────┬───────────┐
│ b   ┆ {"s","x"} ┆ {"f","y"} │
│ --- ┆ ---       ┆ ---       │
│ str ┆ u32       ┆ u32       │
╞═════╪═══════════╪═══════════╡
│ a   ┆ 1         ┆ null      │
│ b   ┆ null      ┆ 1         │
└─────┴───────────┴───────────┘
```

**Comment by SailingZhou** [comment]
AWESOME news~ Thank you for letting me know!
