### ISSUE TITLE
separator in pivot function

### ISSUE THREAD

**Issue by SailingZhou** [pola-rs/nodejs-polars#180]
#### Describe your feature request

Could we have the separator feature for pivot function like the ones in python version?

* separator
Used as separator/delimiter in generated column names. 

https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.pivot.html

Thanks in advance!

**Comment by Bidek56** [comment]
Do you know how the separator option works in Python? B/c adding it to this code does not seem to do anything. Thx

```
import polars as pl

df = pl.DataFrame({'a':['beep', 'bop'],'b':['a','b'],'c':['s','f'],'d':[7,8], 'e':['x', 'y']})
df2 = df.pivot(values=['a'], index='b', columns=['c', 'e'], aggregate_function='len', separator="|")
```

**Comment by SailingZhou** [comment]
```
 df = pl.DataFrame({'a': ['beep', 'bop'], 'b': ['a', 'b'], 'c': ['s', 'f'], 'd': [7, 8], 'e': ['x', 'y']})
    print(df)
    df2 = df.pivot(values=['a', 'e'], index='b', columns=['c'], aggregate_function='first', separator="|")
    print(df2.columns)
    print(df2)
```

Will result in 
![image](https://github.com/pola-rs/nodejs-polars/assets/38984050/2a4b98d4-d432-462d-b454-4816c14df6d2)
