### ISSUE TITLE
Series constructor ignores dtype

### ISSUE THREAD

**Issue by richard-vock** [pola-rs/nodejs-polars#186]
#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.9.0

#### What operating system are you using polars on?

NixOS unstable

#### What node version are you using?

node 20.11.0 

#### Describe your bug.

```
 pl.Series("index", [1, 2, 3], pl.Int64)
```

yields:

```
 shape: (3,)
 Series: 'index' [f64]
 [
   1.0
   2.0
   3.0
]
```

**Comment by Bidek56** [comment]
Hmm, this is an interesting one, b/c it works fine in bun:
```
shape: (3,)
Series: 'index' [i64]
[
	1
	2
	3
]
```

But it produces wrong results in node v20.11.1

**Comment by universalmind303** [comment]
@richard-vock can you provide a full MRE? The JS ecosystem has a lot of different module systems, so I wonder if that has some effect here.
