### ISSUE TITLE
Cannot filter for strings

### ISSUE THREAD

**Issue by forgetso** [pola-rs/nodejs-polars#19]
#### Have you tried latest version of polars?

- [x] yes
- [ ] no

#### What version of polars are you using?

`nodejs-polars@0.6.0`

#### What operating system are you using polars on?

```Linux 5.4.0-132-generic #148-Ubuntu```

#### What node version are you using

```
node --version
v16.13.2
```

#### Describe your bug.

Cannot filter for string values 

#### What are the steps to reproduce the behavior?

```javascript
> df = pl.DataFrame({"foo": ["a", "b", "c"]})
Proxy [
  shape: (3, 1)
  ┌─────┐
  │ foo │
  │ --- │
  │ str │
  ╞═════╡
  │ a   │
  ├╌╌╌╌╌┤
  │ b   │
  ├╌╌╌╌╌┤
  │ c   │
  └─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]
> df.filter(pl.col("foo").eq("b"))
Uncaught Error: Not found: b
    at Object.collectSync (/home/user/dev/workspaces/node_modules/nodejs-polars/bin/lazy/dataframe.js:62:53)
    at Proxy.filter (/home/user/dev/workspaces/node_modules/nodejs-polars/bin/dataframe.js:155:18) {
  code: 'GenericFailure'
}
```

#### What is the actual behavior?

The filter fails

#### What is the expected behavior?

The filter should succeed

#### Additional Info

You can get around this error by placing the string value in a series

```
> df = pl.DataFrame({"foo": ["a", "b", "c"]})
Proxy [
  shape: (3, 1)
  ┌─────┐
  │ foo │
  │ --- │
  │ str │
  ╞═════╡
  │ a   │
  ├╌╌╌╌╌┤
  │ b   │
  ├╌╌╌╌╌┤
  │ c   │
  └─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]
> df.filter(pl.col("foo").eq(pl.Series(["b"])))
Proxy [
  shape: (1, 1)
  ┌─────┐
  │ foo │
  │ --- │
  │ str │
  ╞═════╡
  │ b   │
  └─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]

```

**Comment by universalmind303** [comment]
when using strings, you need to use `lit` 

```js
df.filter(pl.col("foo").eq(pl.lit("b"))
```

**Comment by daolanfler** [comment]
I think the [`filter` api's doc](https://pola-rs.github.io/nodejs-polars/interfaces/pl.DataFrame-1.html#filter) needs an update. it's not using `pl.lit` when comparing strings .... 
![image](https://github.com/pola-rs/nodejs-polars/assets/29777079/6e79099c-baba-44d5-9f4f-7cb176c53911)

**Comment by badele** [comment]
I'm using **Polars** with **JavaScript (Deno)**. I spent a considerable amount of time searching through the documentation before stumbling upon this issue (it was the last test I performed before deciding to stop using Polars).

It seems necessary to either create an alias like `compareString` or clearly state in the documentation that, since the Polar version for Node.js, it is now required to use the following code:

```javascript
const scan = await pl.scanCSV("database/.export/symbols_history.csv", {
  sep: ";",
  quoteChar: '"',
  parseDates: true,
}).select(["SYMBOL", "DATE", "Industry", "price"])
  .filter(
    pl.col("SYMBOL").eq(pl.lit("AI")),
  )
  .collect();
```

This could prevent any confusion and facilitate the transition to the new Polar practices."
