### ISSUE TITLE
Expanded expression support for nodejs-polars

### ISSUE THREAD

**Issue by wbeardall** [pola-rs/nodejs-polars#197]
The expression API for nodejs-polars is currently missing a number of very useful mathematical functionality currently implemented in the Python API. Most notably, for my use-cases `polars.Expr.exp`, `polars.Expr.log` (and variants) would be incredibly useful to have access to in nodejs-polars, as would various trigonometric functions.

**Comment by Bidek56** [comment]
We can certainly add them, would you have a more extensive list? Thx

**Comment by wbeardall** [comment]
Thanks for getting back so quickly on this! Ideally a one-for-one recreation of the Python expressions API would be amazing, but my priorities for maximising utility are as follows:

### High

- [`polars.Expr.exp`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.exp.html#polars.Expr.exp)
- [`polars.Expr.log`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.log.html#polars.Expr.log)
- [`polars.Expr.log1p`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.log1p.html#polars.Expr.log1p)

### Medium
- [`polars.Expr.sin`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.sin.html#polars.Expr.sin)
- [`polars.Expr.cos`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.cos.html#polars.Expr.cos)
- [`polars.Expr.tan`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.tan.html#polars.Expr.tan)

### Low
- [`polars.Expr.`]()
- [`polars.Expr.`]()
- [`polars.Expr.`]()
- [`polars.Expr.`]()

**Comment by Bidek56** [comment]
I would love to use syntax like this, but it does not exist yet. :(
`df.withColumns([pl.col("a").map((val) => Math.cos(val)).alias('cos')]);`

**Comment by wbeardall** [comment]
Agreed, that would be really cool if it could be handled in a performant way!
