### ISSUE TITLE
Cannot create dataframe containing null values

### ISSUE THREAD

**Issue by forgetso** [pola-rs/nodejs-polars#20]
#### Have you tried latest version of polars?

- [x] yes
- [ ] no

#### What version of polars are you using?

`0.6.0`

#### What operating system are you using polars on?

`Linux 5.4.0-132-generic #148-Ubuntu`

#### What node version are you using

```
node --version
v16.13.2
```

#### Describe your bug.

Try to create a dataframe with a value that is null results in an unwrap on a None value in rust and a panic.

#### What are the steps to reproduce the behavior?

Try to create a dataframe with a null value

#### What is the actual behavior?

```
node                              
Welcome to Node.js v16.13.2.
Type ".help" for more information.
> pl = require('nodejs-polars')

> pl.DataFrame([{a:1, b:2, c:null}])
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/dataframe.rs:1548:29
```

#### What is the expected behavior?

Polars should have created the dataframe with a null value for column c

```
> pl.DataFrame([{a:1, b:2, c:null}])
Proxy [
  shape: (1, 3)
  ┌─────┬─────┬─────┐
  │ a   ┆ b   ┆ c   │
  │ --- ┆ --- ┆ --- │
  │ f64 ┆ f64 ┆ f64 │
  ╞═════╪═════╪═════╡
  │ 1.0 ┆ 2.0 ┆ null │
  └─────┴─────┴─────┘,
  {
    get: [Function: get],
    set: [Function: set],
    has: [Function: has],
    ownKeys: [Function: ownKeys],
    getOwnPropertyDescriptor: [Function: getOwnPropertyDescriptor]
  }
]
```

**Comment by johanroelofsen** [comment]
While looking into this one, I noticed that providing arrays into the object:

```typescript
const lf = pl.DataFrame({ a: [1], b: [2], c: [null] });
console.log(lf);
``` 

returns 
```
shape: (1, 3)
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ c    │
│ --- ┆ --- ┆ ---  │
│ f64 ┆ f64 ┆ f64  │
╞═════╪═════╪══════╡
│ 1.0 ┆ 2.0 ┆ null │
└─────┴─────┴──────┘
```

Because of this notice of the documentation: 

> Interface DataFrame
> 
> A DataFrame is a two-dimensional data structure that represents data as a table with rows and columns.
> Param
> 
> Object, Array, or Series Two-dimensional data in various forms. object must contain Arrays. Array may contain Series or other Arrays.

I am a little bit hesistant whether I should further check this?

**Comment by forgetso** [comment]
It's probably not a high priority ticket as you've demonstrated a workaround. I am coming from pandas where the other syntax does work.

```
>>> pd.DataFrame([{'a':1, 'b':2, 'c':None}])
   a  b     c
0  1  2  None
```

**Comment by Bidek56** [comment]
Is anyone able to put a PR for this item? 
I am getting the same error when reading data from DB and converting it to an array is not an easy task. 
my sqlite returns: `const lf = pl.DataFrame([{ a: 1, b: 2, c: null }]);` 
then nodejs-polars: `thread '<unnamed>' panicked at 'called Option::unwrap() on a None value', src/dataframe.rs:1527:29`

I have tried to fork and build, but as a Rust beginner, I am running into build issues. Thanks!!

**Comment by Bidek56** [comment]
I have a created a [PR](https://github.com/pola-rs/nodejs-polars/pull/60) for this issue.

**Comment by Bidek56** [comment]
But I do see a problem after my PR. 
`pl.DataFrame([{a:1, b:2, c:null}])` will omit column c, unless one of the rows has a non-null value.

**Comment by universalmind303** [comment]
> But I do see a problem after my PR.
pl.DataFrame([{a:1, b:2, c:null}]) will omit column c, unless one of the rows has a non-null value.

I believe this is a known issue in the polars json parser. which the JS parser is mostly based off of.

https://github.com/pola-rs/polars/issues/7858

**Comment by daolanfler** [comment]
for those who want a temporary solution, you can check if such column in the `df.columns` array. then use `with_columns` to add a column full of `null` values 
```ts
const data3 = [
  { col1: "b", col2: "d", str: "1 -> 1 -> 2", time: 1691565256703, col3: null },
  { col1: "b", col2: "c", str: "2 -> 2 -> 1", col3: null },
  { col1: "c", col2: "a", str: "3 -> 3 -> 3", col3: null },
];

let df3 = pl.DataFrame(data3 );
if (!df3.columns.includes('col3')) {
    df3 = df3.withColumn(pl.lit(null).alias("col3"));
}

┌──────┬──────┬─────────────┬───────────┬──────┐
│ col1 ┆ col2 ┆ str         ┆ time      ┆ col3 │
│ ---  ┆ ---  ┆ ---         ┆ ---       ┆ ---  │
│ str  ┆ str  ┆ str         ┆ f64       ┆ null │
╞══════╪══════╪═════════════╪═══════════╪══════╡
│ b    ┆ d    ┆ 1 -> 1 -> 2 ┆ 1.6916e12 ┆ null │
│ b    ┆ c    ┆ 2 -> 2 -> 1 ┆ null      ┆ null │
│ c    ┆ a    ┆ 3 -> 3 -> 3 ┆ null      ┆ null │
└──────┴──────┴─────────────┴───────────┴──────┘
```
