### ISSUE TITLE
Add support for Decimal DataType

### ISSUE THREAD

**Issue by gustaferiksson** [pola-rs/nodejs-polars#209]
It would be useful to have support for the [Decimal DataType](https://docs.rs/polars/latest/polars/datatypes/enum.DataType.html#variant.Decimal).

It's possible to read and execute on e.g parquet dataframes containing Decimal as type but it doesn't seem to be possible to create or cast new columns with/to Decimal as type.

**Comment by Bidek56** [comment]
I have created a draft #210 but Decimal functionality in Polars is considered unstable, hence I am not sure that we want to add it at this stage.

**Comment by froxCZ** [comment]
+1 on this. The python wrapper does support it, albeit I have no idea how much unstable that is and how much it can change in the future.

**Comment by Bidek56** [comment]
#226 Should address this request. Please close this ticket once you are able to test it. Thx

**Comment by Bidek56** [comment]
Closing via #226
