### ISSUE TITLE
Join suffix has no impact

### ISSUE THREAD

**Issue by jnutter** [pola-rs/nodejs-polars#219]
#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

nodejs-polars 12.2 but tried 11 and 10 with no success either

#### What operating system are you using polars on?

MacOS 14.5

#### What node version are you using

20.9.0

#### Describe your bug.

I am attempting to join 2 pivot tables together. The table being joined always has the suffix `_right`. I do see the correct suffix being passed into `wrap("join", other._df, leftOn, rightOn, how, suffix);` however did not explore deeper.

#### What are the steps to reproduce the behavior?

```js
import pl from 'nodejs-polars';

const df1 = pl.DataFrame({
  id: [1, 2, 3],
  name: ['Alice', 'Bob', 'Charlie'],
});

const df2 = pl.DataFrame({
  id: [1, 2, 4],
  name: ['Alice2', 'Bob2', 'Charlie2'],
});

// Perform a join operation
const joinedDF = df1.join(df2, { on: 'id', how: 'inner', suffix: '_clone' });

console.log(joinedDF.toString());
```

#### What is the actual behavior?

```
┌─────┬───────┬────────────┐
│ id  ┆ name  ┆ name_right │
│ --- ┆ ---   ┆ ---        │
│ f64 ┆ str   ┆ str        │
╞═════╪═══════╪════════════╡
│ 1.0 ┆ Alice ┆ Alice2     │
│ 2.0 ┆ Bob   ┆ Bob2       │
└─────┴───────┴────────────┘
```

#### What is the expected behavior?

```
┌─────┬───────┬────────────┐
│ id  ┆ name  ┆ name_clone │
│ --- ┆ ---   ┆ ---        │
│ f64 ┆ str   ┆ str        │
╞═════╪═══════╪════════════╡
│ 1.0 ┆ Alice ┆ Alice2     │
│ 2.0 ┆ Bob   ┆ Bob2       │
└─────┴───────┴────────────┘
```

What do you think polars should have done?

Change name_right to name_clone

**Comment by Bidek56** [comment]
@jnutter Thx for pointing this out!!
