### ISSUE TITLE
Issue with scoped package

### ISSUE THREAD

**Issue by alex-patow** [pola-rs/nodejs-polars#25]
#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?
0.7.1

#### What operating system are you using polars on?

MacOS

#### What node version are you using
node 16.14.0 

#### Describe your bug.
Getting a typescript "cannot find module" error when trying to use the latest version of Polars.

#### What are the steps to reproduce the behavior?
Install latest version, try to import it.

```
npm install nodejs-polars --save 

--

import * as pl from 'nodejs-polars';
```

#### What is the actual behavior?

```
node_modules/nodejs-polars/bin/series/series.d.ts:9:37 - error TS2307: Cannot find module '@polars/lazy/expr' or its corresponding type declarations.

9 import { InterpolationMethod } from "@polars/lazy/expr";
                                      ~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/nodejs-polars/bin/series/series.d.ts:9
```

#### What is the expected behavior?
It should import.

What do you think polars should have done?

I think this line is the culprit: https://github.com/pola-rs/nodejs-polars/pull/22/files#diff-593c508a021e0588e493c0b6207a578a7237471bca1892b20eaee7a4f0736930R13 

If I've searched correctly, it looks like the only place in the repo which uses that namespaced import, so maybe just revert it to the regular syntax? Happy to open a PR if you'd like me to.

**Comment by universalmind303** [comment]
Yes a PR would be much appreciated. Looks like my auto import went awry and somehow the CI didn't catch it.

**Comment by alex-patow** [comment]
Cool, opened one! Seemed like the only place where that polars was being imported like that
