### ISSUE TITLE
toRecords() return "invalid date" on datetime[ns] col in Dataframe

### ISSUE THREAD

**Issue by sherlockwang** [pola-rs/nodejs-polars#259]
#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.15

#### What operating system are you using polars on?

Linux

#### What node version are you using

v21.5.0

#### Describe your bug.

I use nodejs-polars to read a DateFrame from a parquet file generated by polars Python. There are several col in datetime[ns] type. However, when I use DateFrame.toRecords() to transfer DateFrame into JS array, the methods return "invalid date" on datetime[ns] col.

#### What are the steps to reproduce the behavior?

Have a parquet file with datetime[ns] type col. (date.parquet in example)

**Example**

```js
import pl from "nodejs-polars"

const df = pl.readParquet(path.join(process.cwd(), 'data', 'date.parquet'))

console.log(df.getColumn('created'))

const output = df.toRecords()

console.log(output)

/** output in console
Series: 'created' [datetime[ns]]
[
        2024-08-22 17:01:09
        2024-07-04 10:52:15
        2024-08-07 16:34:59
        2024-08-15 17:56:37
        2024-07-31 18:16:23
        2024-08-15 14:27:27
]
[
  {
    ...
    created: Invalid Date,
    ...
  },
  ...
]
*/
```

#### What is the actual behavior?

Invalid Date

#### What is the expected behavior?

Date Object or Timestamp

What do you think polars should have done?

I think the issue comes from toRecords() itself doesn't convert datatime[ns] type into JS Date object correctly, because js cannot handle ns timestamp.

**Comment by Bidek56** [comment]
Can you please provide a MRE, b/c this works fine for me. I create the `.parquet` using `py-polars`
```
import polars as pl

data = {
    'hi': [True, False, True, False],
    'bye': [1, 2, 3, 4],
    'dt': [ "2024-08-22 17:01:09",
        "2024-07-04 10:52:15",
        "2024-08-07 16:34:59",
        "2024-08-15 17:56:37"]
}

df = pl.DataFrame(data).with_columns(pl.col("dt").str.to_datetime().cast(pl.Datetime("ms")).alias("dt"))
print(df)

df.write_parquet("dates.parquet")
```
I get this DF:
```
shape: (4, 3)
┌───────┬─────┬─────────────────────┐
│ hi    ┆ bye ┆ dt                  │
│ ---   ┆ --- ┆ ---                 │
│ bool  ┆ i64 ┆ datetime[ms]        │
╞═══════╪═════╪═════════════════════╡
│ true  ┆ 1   ┆ 2024-08-22 17:01:09 │
│ false ┆ 2   ┆ 2024-07-04 10:52:15 │
│ true  ┆ 3   ┆ 2024-08-07 16:34:59 │
│ false ┆ 4   ┆ 2024-08-15 17:56:37 │
└───────┴─────┴─────────────────────┘
```
The when I read the `dates.parquet` using `nodejs-polars` using this code:

```
import { pl } from "nodejs-polars";
const pqFile = "dates.parquet";

const df2 = pl.readParquet(pqFile);

console.log(df2);
console.log(JSON.stringify(df2.toRecords()));
```
 I get:
```
shape: (4, 3)
┌───────┬─────┬─────────────────────┐
│ hi    ┆ bye ┆ dt                  │
│ ---   ┆ --- ┆ ---                 │
│ bool  ┆ i64 ┆ datetime[ms]        │
╞═══════╪═════╪═════════════════════╡
│ true  ┆ 1   ┆ 2024-08-22 17:01:09 │
│ false ┆ 2   ┆ 2024-07-04 10:52:15 │
│ true  ┆ 3   ┆ 2024-08-07 16:34:59 │
│ false ┆ 4   ┆ 2024-08-15 17:56:37 │
└───────┴─────┴─────────────────────┘
[{"hi":true,"bye":1,"dt":"2024-08-22T17:01:09.000Z"},{"hi":false,"bye":2,"dt":"2024-07-04T10:52:15.000Z"},{"hi":true,"bye":3,"dt":"2024-08-07T16:34:59.000Z"},{"hi":false,"bye":4,"dt":"2024-08-15T17:56:37.000Z"}]
```

**Comment by sherlockwang** [comment]
Hi there,

Thanks for the fast reply. I have tried your method, and it works well. 

However, the solution is actually convert datetime [ns] type to datetime [ms] type in Python, which seems reasonable in my case, but need extra work on every datetime [ns] columns. Since there is no datetime [ns] type in node JS, I think it may be better to embed this transformation in node JS library toRecords() method to automatically change unsupported datatype. What do you think? May be it is better to be a feature request than a bug? 

Anyway, thanks again for your help. It really save me a lot of time. Have a nice day!

**Comment by Bidek56** [comment]
Feel free to put a PR for toRecords() method to automatically change unsupported datatype, but I am not sure that is possible.

**Comment by universalmind303** [comment]
given js has no native `datetime [ns]` type, an explicit cast will be always be needed. 

Ideally, we'd have column selectors in JS too, and you could cast all `datetime[ns]` to `datetime[ms]` that way instead.
