### ISSUE TITLE
sorting not working in reverse.

### ISSUE THREAD

**Issue by paladinic** [pola-rs/nodejs-polars#276]
#### Have you tried latest version of polars?
- [yes]

#### What version of polars are you using?
"nodejs-polars": "^0.15.0",

#### What operating system are you using polars on?
Windows 11

#### What node version are you using
Node.js v20.17.0

#### Describe your bug.
The sorting method does not sort in reverse. I found this on dataframes as well as with series like the ones in the [documentation](https://pola-rs.github.io/nodejs-polars/#md:series).

#### What are the steps to reproduce the behavior?
```
let fooSeries = pl.Series("foo", [4, 1, 2, 3])
const fooSeriesRev = fooSeries.sort({reverse: true})
fooSeries = fooSeries.sort({reverse: false})

console.log( fooSeries);
console.log( fooSeriesRev);
```

#### What is the actual behavior?
```
Series: 'foo' [f64]
[
        1.0
        2.0
        3.0
        4.0
]
shape: (4,)
Series: 'foo' [f64]
[
        1.0
        2.0
        3.0
        4.0
]
```

#### What is the expected behavior?
Sort the series in reverse.
```
Series: 'foo' [f64]
[
        1.0
        2.0
        3.0
        4.0
]
shape: (4,)
Series: 'foo' [f64]
[
        4.0
        3.0
        2.0
        1.0
]
```

**Comment by paladinic** [comment]
temporary work around using ` .mul(-1)` to achieve reverse sorting.

**Comment by Bidek56** [comment]
Please use: `const fooSeriesRev = fooSeries.sort({descending: true});` Thx

**Comment by paladinic** [comment]
ok, thanks. 
⚠️`reverse` is all over the documentation though.
