### ISSUE TITLE
build failing for ARM

### ISSUE THREAD

**Issue by universalmind303** [pola-rs/nodejs-polars#280]
running `yarn build` fails for ARM architectures currently. 

https://github.com/pola-rs/nodejs-polars/actions/runs/10997282428/job/30532443563?pr=269

**Comment by Bidek56** [comment]
I guess we should be using a [crate](https://crates.io/crates/polars-parquet) here to avoid this issue.

**Comment by Bidek56** [comment]
This is related to [this](https://github.com/rust-lang/rust/issues/129887) Rustc issue.
