### ISSUE TITLE
Polars scan parquet not detecting additional columns in some partitions

### ISSUE THREAD

**Issue by Sankartk** [pola-rs/nodejs-polars#283]
#### Have you tried latest version of polars?

Yes

#### What version of polars are you using?

1.19.0

#### What operating system are you using polars on?

WINDOWS 11

#### Describe your bug.

I'm using polars scan parquet method to read parquet files from a directory path which has partitions. For some partitions, the file has new columns added where polars is not scanning those. I also tried allowing missing columns equals true even that didn't fix the error

**Comment by Bidek56** [comment]
@Sankartk Do you have a MRE? Do you experience this problem using `Python-polars`?
Have you tried to look for a solution in SO? Thx

**Comment by Sankartk** [comment]
Yes python polars. I tried to look at the solution where they asked to use allow_missing_columns= True field on using scan_parquet method but that didn't help as well

**Comment by Bidek56** [comment]
This is a Python Polars issue, not a Nodejs issue.
