### ISSUE TITLE
Add support for `allowMissingColumns` flag in nodejs-polars client

### ISSUE THREAD

**Issue by mostopalove** [pola-rs/nodejs-polars#284]
**Description:**
I would like to request the addition of support for the `allowMissingColumns` flag in the Node.js client, similar to its current implementation in the Python client.

This feature is documented in the Python API here:
[Polars Python Documentation - allow_missing_columns](https://docs.pola.rs/api/python/stable/reference/api/polars.scan_parquet.html)

In the Node.js client, the current available options for `ScanParquetOptions` can be found here:
[Node.js Polars Documentation - ScanParquetOptions](https://pola-rs.github.io/nodejs-polars/interfaces/ScanParquetOptions.html)

**Feature Request:**
Please consider adding the `allowMissingColumns` flag to the Node.js client's `ScanParquetOptions` to provide consistency across different client implementations.

In addition, this feature should help resolve errors like `"Error: schemas contained differing number of columns"`, which arise when loading parquet files with schema inconsistencies between different files.

Thank you for considering this request!

**Comment by Bidek56** [comment]
`allow_missing_columns` was just added to to Polars, we need let it bake a bit and be added to a RS release first. :)

**Comment by universalmind303** [comment]
the rust release cadence is a bit slower than Python. [Historically](https://crates.io/crates/polars/versions), it looks like there's a release every 1-2 months
