### ISSUE TITLE
Infer schema with empty array causes index out of bounds exception

### ISSUE THREAD

**Issue by tmckenn2** [pola-rs/nodejs-polars#296]
#### Have you tried latest version of polars?

yes

#### What version of polars are you using?

0.16.0

#### What operating system are you using polars on?

OS X 15.1

#### What node version are you using

Deno 2.0.6

#### Describe your bug.

An array index out of bounds exception is thrown when building a DataFrame from records, if an array column contains an empty array. Polars should be able to infer the schema as long as one array in the column is nonempty.

#### What are the steps to reproduce the behavior?

```js
import pl from "nodejs-polars"

pl.DataFrame([
  {  a: [], b: 0 }, 
  {  a: [""], b: 0 }
])
```

#### What is the actual behavior?

```
error: Uncaught (in promise) Error: index out of bounds: the len is 0 but the index is 0
    at arrayToJsDataFrame ([REDACTED]/nodejs-polars/0.16.0/bin/internals/construction.js:197:46)
    at Module.DataFrameConstructor ([REDACTED]/nodejs-polars/0.16.0/bin/dataframe.js:730:78)
    at [REDACTED]/polars.ts:3:19
```

#### What is the expected behavior?

produce a schema:

```js
{
  a: pl.List(pl.String),
  b: pl.Float64,
}
```

**Comment by Bidek56** [comment]
Can you please either do a PR or post your solution/fix here? Thx

**Comment by tmckenn2** [comment]
I added a PR. I could see handling this in coerce_data_type instead.
