### ISSUE TITLE
pl.readCSV doesn't understand http links

### ISSUE THREAD

**Issue by sigmaSd** [pola-rs/nodejs-polars#35]
```js
const pl  = require("nodejs-polars");
const df = pl.readCSV("https://j.mp/iriscsv")
console.log(df)
```

it doesn't download the link, but instead just use the string in a table
![image](https://user-images.githubusercontent.com/22427111/212489699-69f06b91-1d96-40d2-8854-7a9e5bd23933.png)

Also another issue pl.all() seems to be not reexported https://github.com/pola-rs/nodejs-polars/blob/da804fcbdc068f99f44288b50af2ba534b4774aa/polars/lazy/functions.ts#L170

I'm just following the book https://pola-rs.github.io/polars-book/user-guide/quickstart/intro.html and writing the issues I find

**Comment by Bidek56** [comment]
We have decided not to to add URL functionality to `readCSV` since it's easy enough to use Node fetch method and read from a buffer.

```
const URL = "https://j.mp/iriscsv"
const df = await fetch(URL)
          .then(async (res) => Buffer.from(await res.arrayBuffer()))
          .then((buf) => pl.readCSV(buf))
```
