### ISSUE TITLE
`readJson` throws fatal error

### ISSUE THREAD

**Issue by rschwabco** [pola-rs/nodejs-polars#42]
#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using? 

0.7.2

#### What operating system are you using polars on?

macOS Ventura Version 13.1 (22C65)

#### What node version are you using
ex: node 18.12.1 

#### Describe your bug.

Using `readJson` results in a fatal error.

#### What are the steps to reproduce the behavior?

```
import pl from "nodejs-polars"

  const jsonString = `
{"a", 1, "b", "foo", "c": 3}
{"a": 2, "b": "bar", "c": 6}
`
const df = pl.readJSON(jsonString)

```

#### What is the actual behavior?

Full trace: 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ExternalFormat("InvalidToken(44)")', /Users/runner/.cargo/git/checkouts/polars-b0d90607192fd414/43598c3/polars/polars-io/src/ndjson_core/ndjson.rs:161:90
stack backtrace:
   0:        0x12325a7b8 - _napi_register_module_v1
   1:        0x12327688c - _napi_register_module_v1
   2:        0x123257750 - _napi_register_module_v1
   3:        0x12325a5cc - _napi_register_module_v1
   4:        0x12325bd40 - _napi_register_module_v1
   5:        0x12325ba98 - _napi_register_module_v1
   6:        0x12325c364 - _napi_register_module_v1
   7:        0x12325c184 - _napi_register_module_v1
   8:        0x12325ac20 - _napi_register_module_v1
   9:        0x12325bee0 - _napi_register_module_v1
  10:        0x12334f078 - _napi_register_module_v1
  11:        0x12334f260 - _napi_register_module_v1
  12:        0x1223e9c34 - <unknown>
  13:        0x121ebb94c - <unknown>
  14:        0x121ebc12c - <unknown>
fatal runtime error: failed to initiate panic, error 5
```

#### What is the expected behavior?
Should read the JSON string properly

What do you think polars should have done?
Should have read the JSON string properly

**Comment by universalmind303** [comment]
I think this is a bug in the version of the json-deserializer we are using. I believe this is fixed in the latest version. I'll try to update nodejs-polars dependencies

**Comment by Bidek56** [comment]
0.8.2 throw valid error for invalid JSON: `Error: ExpectedObjectColon at character 4 (',')`
