### ISSUE TITLE
 Cannot find module 'nodejs-polars-linux-arm64-musl'

### ISSUE THREAD

**Issue by murunwas** [pola-rs/nodejs-polars#43]
#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?
0.7.2

#### What operating system are you using polars on?
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1027 aarch64)

#### What node version are you using
node 16.19.0

#### Describe your bug.
getting ` Cannot find module 'nodejs-polars-linux-arm64-musl'`  error

**Comment by universalmind303** [comment]
i think https://github.com/pola-rs/nodejs-polars/pull/34 fixed this. I should have some time to push up a new version `0.7.3` that should support your target sometime this week

**Comment by Bidek56** [comment]
@murunwas Please verify that 0.8.2 works for fine and close this ticket. Thx
