### ISSUE TITLE
Failed to create napi buffer, when use `dataframe.toJson()`

### ISSUE THREAD

**Issue by chaozwn** [pola-rs/nodejs-polars#44]
#### Have you tried latest version of polars?

yes

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

Replace this text with the version.

#### What operating system are you using polars on?

Replace this text with your operating system and version.

#### What node version are you using
ex: node 16.10.0 

#### Describe your bug.
Failed to create napi buffer, when use `dataframe.toJson()`
![image](https://user-images.githubusercontent.com/51357674/220910318-268d821c-0c47-40ed-88d7-d951c133b0c0.png)
but when i set params space string,it works well.
![image](https://user-images.githubusercontent.com/51357674/220910901-72d2ba41-b93a-46b0-8edf-76e9788f8a6d.png)

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example on a dataset that is created through code:

Please use code instead of images, we don't like typing.

If the example is large, put it in a gist: https://gist.github.com/

If the example is small, put it in code fences:

```
your
code
goes
here
```

**Example**

```js
import pl from "nodejs-polars"

// Create a simple dataset on which we can reproduce the bug.
pl.DataFrame({
    "foo": [None, 1, 2],
    "bar": [1n,2n,3n]
})
```

If we cannot reproduce the bug, it is unlikely that we will be able fix it.

Please remove clutter from your examples. Only include the bare minimum to produce the result.
So please:

* strip unused columns
* use short distinguishable names
* don't include unneeded computations

#### What is the actual behavior?

Show the query you ran and the actual output. 

If the output is large, put it in a gist: https://gist.github.com/

If the output is small, put it in code fences:

```
your
output
goes
here
```

#### What is the expected behavior?

What do you think polars should have done?

**Comment by universalmind303** [comment]
`toJSON` mainly exists for interop with `JSON.stringify`, and should not be used directly. Please use either `writeJSON` or `JSON.stringify(df)`.
