### ISSUE TITLE
`toRecords` fails to convert `pl.Date` values

### ISSUE THREAD

**Issue by kymckay** [pola-rs/nodejs-polars#48]
#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

- 0.7.2

#### What operating system are you using polars on?

- Debian 12

#### What node version are you using

- node 18.13.0

#### Describe your bug.

- With a `pl.Date` column in the data frame, using the `toRecords` function produces objects which have dates at the unix epoch.

#### What are the steps to reproduce the behavior?

```ts
import pl from "nodejs-polars";

let df = pl.DataFrame({
  date: [new Date()],
});

df = df.withColumn(pl.col("date").cast(pl.Date).alias("date"));

console.log(df.toString());
console.log(df.toRecords());
```

#### What is the actual behavior?

```
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2023-03-09 │
└────────────┘

{date: Thu Jan 01 1970 01:00:19 GMT+0100 (Greenwich Mean Time)}
```

#### What is the expected behavior?

```
shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2023-03-09 │
└────────────┘

{date: Thu Mar 09 2023 00:00:00 GMT+0100 (Greenwich Mean Time)}
```

**Comment by Bidek56** [comment]
This works in 0.8.0: 

```
let df = pl.DataFrame({
  date: [new Date()],
});

df = df.withColumn(pl.col("date").date.strftime("%Y-%m-%d").alias("date"));

console.log(df.toString());
console.log(df.toRecords());

shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ str        │
╞════════════╡
│ 2023-06-18 │
└────────────┘
[ { date: '2023-06-18' } ]
```

**Comment by kymckay** [comment]
I think you have misunderstood, as your example is different since it's just converting a `pl.Datetime` column into strings.

I'm interested in storing `pl.Date` type in the dataframe, which should map to `Date` objects in the records form (`pl.Datetime` works correctly and can be used as a workaround, but I don't need that precision, just the date).

**Comment by Bidek56** [comment]
@universalmind303 Something is happening during `col.get(idx);` on this [line](https://github.com/pola-rs/nodejs-polars/blob/f485fea5c8cd40ff35ace76ac60dc73ab071bd6f/src/dataframe.rs#L1242)
Would you be able to shade some light? Thx

**Comment by Bidek56** [comment]
The code above works fine in 0.8.2, please re-open is this still an issue. Thx
