### ISSUE TITLE
I/O compatibility with Bun.js

### ISSUE THREAD

**Issue by Jonarod** [pola-rs/nodejs-polars#49]
#### What version of polars are you using?

0.7.2

#### What operating system are you using polars on?

Mac M1

#### What node version are you using

v16.18.0

but this is a request/question regarding bun.js compatibility. My bun.js version is v0.5.7

#### Describe your bug.

Using `bun.js` instead of Node.js, when I try to use any `I/O` functions like `pl.readCSV()` or `pl.scanCSV()`, `bun.js` crashes giving this error:

```bash
bun index.js
125 |     parseDates: false,
126 |     skipRowsAfterHeader: 0
127 | };
128 | function scanCSV(path, options) {
129 |     options = { ...scanCsvDefaultOptions, ...options };
130 |     return (0, dataframe_2._LazyDataFrame)(polars_internal_1.default.scanCsv(path, options));
                                              ^
error: InvalidArg
      at scanCSV (/Users/home/Documents/js_backtest_engine/node_modules/nodejs-polars/bin/io.js:130:43)
      at /Users/home/Documents/js_backtest_engine/index.js:32:9
```

#### What are the steps to reproduce the behavior?

```js
import pl from "nodejs-polars"

let df = pl.readCSV('data.csv')
```

I understand the library is called `nodejs`-polars and `bun.js` is not even in the map (nor should it be i guess) and in that sense the issue is more related to `bun` compatibility with `node` than an issue with the polars' bindings itself. That being said, since the package is aimed at extracting the most performance from JS in general, I can see `bun` is consistently 2x-10x faster than Node in quite any situation really, and it also shows when manipulating `Dataframes` with `nodejs-polars`. Hence I wondered I'd give it a shot to ask if anyone has any idea why such error appears and if anything could make the `I/O` functions compatible with `bun` too?

Note that, as I mentionned, `Dataframe` and `Series` do work like a charm with `bun`, so this is specifically something going on with `I/O`. I reckon that to create a stream in `bun` I do `const stream = Bun.file(this.filePath).stream();` instead of `const stream = fs.createReadStream(this.filePath);` with Node. So I thought I'd allow myself to post this bug in case some quick fix/workaround could be found.

**Comment by Jarred-Sumner** [comment]
This is a bug in Bun, not in Polars

We fixed a bug similar to this today. Can you try in the canary build of Bun? 

```
bun upgrade --canary
```

**Comment by Jonarod** [comment]
I am new to Rust so please correct me if I am wrong here but, I see the code heavily uses `polars_internals` which itself relies on binaries compiled with Rust. Isn't all the `I/O` heavy lifting done right in those binaries? What I know is that `Bun` does not use the same `I/O` mechanisms as `Node`. As a simple example, a stream is created differently whether we are in Bun or Node:

Node
```js
const stream = fs.createReadStream(this.filePath);
```

Bun
```js
const stream = Bun.file(this.filePath).stream();
```
So it looks to me that they just don't use the same interface regarding I/O. I have really no clue if this could be the cause of the issue with Bun. That's just my understandings.

Do you think that could be related? If yes, is it a big patch/leap to make Bun compatible?

In the back I guess I could load CSV the classic way using libraries or custom parser, and maybe serialize the resulting schema as a polars Dataframe afterwards to still leverage Bun's power. Is that possible?

Of course, if you feel like Bun should be out of scope don't bother. I was hoping it could be a simple fix :)
Thanks

**Comment by universalmind303** [comment]
So the wrapper methods done in TS have some node.js specific logic, but within polars_internals, it does not operate within Bun or Node at all, but within a native binary that interacts with the runtime (node, bun) via the Node API. ([N-API](https://nodejs.org/api/n-api.html)). 

In theory, if Bun is 100% compatible with the N-API, you should be able to use the bindings directly, but may need some additional logic in the wrappers to handle Bun specific apis. 

I'm not familiar enough with Bun.js to know what exactly would need to be done within the wrapper code to be able to run via Bun. 

For the `readCSV` function, the only node.js specific code is around checking if the argument is a buffer 

```js
  if (Buffer.isBuffer(pathOrBody)) {...}
```

and converting a string to a buffer
```js
      const buf = Buffer.from(pathOrBody, "utf-8");
```

If those are supported via Bun, it _should_ work.

**Comment by danscan** [comment]
I'm encountering the same `error: InvalidArg` issue on Bun `0.6.9` for I/O as well – interestingly, the error occurs even if I pass a Buffer instead of a file path, so it appears not to be related to filesystem calls?

## Using File Path
```typescript
const dataframe = pl.readParquet(filepath);
```
```
188 |         const inline = !(0, utils_1.isPath)(pathOrBody, [".parquet"]);
189 |         if (inline) {
190 |             return (0, dataframe_1._DataFrame)(polars_internal_1.default.readParquet(Buffer.from(pathOrBody), pliOptions, parallel));
191 |         }
192 |         else {
193 |             return (0, dataframe_1._DataFrame)(polars_internal_1.default.readParquet(pathOrBody, pliOptions, parallel));
                                                  ^
error: InvalidArg
      at /redacted/node_modules/nodejs-polars/bin/io.js:193:47
```

## Using Buffer
```typescript
const dataframe = pl.readParquet(
  Buffer.from(await Bun.file(filepath).arrayBuffer())
);
```
```
180 |     }
181 |     pliOptions.nRows = options?.numRows;
182 |     pliOptions.rowCount = options?.rowCount;
183 |     const parallel = options?.parallel ?? "auto";
184 |     if (Buffer.isBuffer(pathOrBody)) {
185 |         return (0, dataframe_1._DataFrame)(polars_internal_1.default.readParquet(pathOrBody, pliOptions, parallel));
                                              ^
error: InvalidArg
      at /redacted/node_modules/nodejs-polars/bin/io.js:185:43
```

**Comment by Bidek56** [comment]
@Jonarod  This code works fine for me using `"nodejs-polars": "^0.8.0"`, can you please confirm it? Thx
```
import pl from "nodejs-polars"
const df = pl.readCSV("data.csv")
```

**Comment by Jarred-Sumner** [comment]
In Bun v0.6.13, we fixed some bugs in NAPI which should address this

**Comment by Bidek56** [comment]
@Jonarod Please close this ticket is you are happy with the fix in Bun. Thx

**Comment by Jonarod** [comment]
After upgrading Bun `bun upgrade` and installing latest `npm i nodejs-polars@0.8.0` I/O ops work like a charm :) 
Thank you very much for all the efforts to make it happen !
