### ISSUE TITLE
Catching errors

### ISSUE THREAD

**Issue by sezanzeb** [pola-rs/nodejs-polars#54]
This is just something I threw into the node console to see what happens:

```js
const pl = require('nodejs-polars');
df = pl.DataFrame()
try { df.withColumn(pl.arange(0, 5).alias('foo').cast('asdf')) } catch(e) { console.error(e) }
thread '<unnamed>' panicked at 'not yet implemented', src/conversion.rs:596:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    27374 IOT instruction (core dumped)  node
```

This just crashes the complete node runtime, I can't catch errors.

I don't know anything about rust, but I guess there is some sort of exception handling there as well? Can errors be made to bubble up into node?

**Comment by universalmind303** [comment]
yes, napi supports catching panics. 

We would need to go through all of the function definitions & add the `catch_unwind` to the napi macros

ex: 

```rust
    #[napi]
    pub fn groupby(...)
```
gets changed to 

```rust
    #[napi(catch_unwind)]
    pub fn groupby(...)
```

**Comment by sezanzeb** [comment]
I wanted to give it a try. But I can't import the binary in my project. Here are all of my steps:

```bash
sudo pacman -S rustup cargo
rustup update -- nightly
git clone git@github.com:pola-rs/nodejs-polars.git
cd nodejs-polars
nvm use 18  # because my project uses node 18
yarn
yarn build:debug && yarn build:ts
```

in my project:

```
yarn add /home/tobias/Code/nodejs-polars
node
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> const pl = require('nodejs-polars'); 
Uncaught Error: Cannot find module 'nodejs-polars-linux-x64-gnu'
Require stack:
- /home/tobias/Code/foo/node_modules/nodejs-polars/bin/native-polars.js
- /home/tobias/Code/foo/node_modules/nodejs-polars/bin/internals/polars_internal.js
- /home/tobias/Code/foo/node_modules/nodejs-polars/bin/series/index.js
- /home/tobias/Code/foo/node_modules/nodejs-polars/bin/index.js
- <repl>
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tobias/Code/foo/node_modules/nodejs-polars/bin/native-polars.js',
    '/home/tobias/Code/foo/node_modules/nodejs-polars/bin/internals/polars_internal.js',
    '/home/tobias/Code/foo/node_modules/nodejs-polars/bin/series/index.js',
    '/home/tobias/Code/foo/node_modules/nodejs-polars/bin/index.js',
    '<repl>'
  ]
}
> 
```

Idk, I don't really know what I'm doing

**Comment by universalmind303** [comment]
@sezanzeb If you want to run it locally, 

```sh
git clone git@github.com:pola-rs/nodejs-polars.git
cd nodejs-polars
nvm use 18 
yarn
yarn build:debug
yarn build:ts
# I don't think this specific step is documented anywhere,
# but you need to copy over the `.node` file from `./polars` to `./bin`
yarn cp:bin
```

Then you can run it locally by requiring `./bin` 
```sh
 node -e "const pl = require('./bin'); console.log(pl.DataFrame({a: [1]}));"
```

**Comment by sezanzeb** [comment]
Thanks. I'll definitely take care of this sooner or later, because I need this at work for a current project, unless someone else happens to do it in the meantime. But earliest next week

**Comment by sezanzeb** [comment]
Turns out error handling in Rust is a bit more complicated than I thought. Also, just replacing every usage of `#[napi]` with `#[napi(catch_unwind)]` causes some compilation errors.

Maybe someone should do this who is not completely new to rust.

**Comment by Harshil-Jani** [comment]
Hey !! I can confirm that If try is successful then it has no problems. But the main concern is  with the condition when try fails and we have to move to the catch block. So, You want to print the catch error over there right ? Or just the message saying that For Eg : "try catch failed" ?

> This also crashes the runtime:

**Comment by ChakshuGautam** [comment]
@Harshil-Jani I would appreciate an error object in node so that I can handle it in the host env. Thanks.

**Comment by dhruv-1001** [comment]
> 

This actually doesn't crash at runtime. There is a check for index in `ploars` which checks the if the index is out of bounds. And if it is, the code just exists. Link - https://github.com/pola-rs/polars/blob/43598c3e21a2b6c1246a565005045ef553e4f688/polars/polars-core/src/chunked_array/ops/take/take_single.rs#L13-L15

It's now fixed and when updated with latest `polars` release `nodejs-polars` would panic as in this case.

**Comment by dhruv-1001** [comment]
> This also crashes the runtime:
> 
> ```js
> try {
> 	console.log(pl.Series([1, 2]).get(2));
> } catch (e) {
> 	// never reached
> 	console.log(e);
> }
> ``` 

This actually doesn't crash at runtime. There is a check for index in `ploars` which checks the if the index is out of bounds. And if it is, the code just exists. Link - https://github.com/pola-rs/polars/blob/43598c3e21a2b6c1246a565005045ef553e4f688/polars/polars-core/src/chunked_array/ops/take/take_single.rs#L13-L15

It's now fixed and when updated with latest `polars` release `nodejs-polars` would panic as in this case.
