### ISSUE TITLE
Regression: Property 'when' does not exist on type 'typeof pl'

### ISSUE THREAD

**Issue by kymckay** [pola-rs/nodejs-polars#62]
#### Have you tried latest version of polars?

- yes

#### What version of polars are you using?

0.7.3

#### What operating system are you using polars on?

Linux amd x64 (Debian 12)

#### What node version are you using

node 18.13.0

#### Describe your bug.

Awesome to see a new release of this (as I've been working around some of the open issues and missing features). It looks like from 0.7.2 to 0.7.3 there was a regression (perhaps intentional) and the `when` function no longer exists as a property of the default export.

#### What are the steps to reproduce the behavior?

This was caught by my CI trying to compile my typescript on the upgrade PR.

**Example**

```ts
import pl, { LazyDataFrame } from "nodejs-polars";

function transform(data: LazyDataFrame): LazyDataFrame {
  return data.withColumn(
    pl
      .when(pl.lit(true))
      .then(pl.lit("Positive"))
      .otherwise(pl.lit("Negative"))
      .alias("someCol")
  );
}
```

#### What is the actual behavior?

> error TS2339: Property 'when' does not exist on type 'typeof pl'.

Can be fixed by importing `when` directly.

#### What is the expected behavior?

Works as did previously.

#### What do you think polars should have done?

Either included this change in the changelog (if intentional) or not introduced a regression

**Comment by Bidek56** [comment]
This is fixed in [0.8.0](https://github.com/pola-rs/nodejs-polars/releases/tag/nodejs-polars-v0.8.0)
