### ISSUE TITLE
nodejs-polars 0.6 npm package is broken

### ISSUE THREAD

**Issue by antonkulaga** [pola-rs/nodejs-polars#7]
When I add nodejs-polars to my package json it for some reasons asks:
```
? Please choose a version of "nodejs-polars-android-arm64" from this list: (Use arrow keys)
❯ 0.5.4 
  0.5.3 
  0.5.2 
  0.5.1 
  0.5.0 
```

It looks really strange as I have regular Linux Mint 21 there. While I have no issues like this with 0.5.4 version

**Comment by universalmind303** [comment]
This should be fixed on the latest version
