### ISSUE TITLE
feature: add `Binary` dtype

### ISSUE THREAD

**Issue by flow-danny** [pola-rs/nodejs-polars#74]
#### Have you tried latest version of polars?

- yes

If the problem was resolved, please update polars. :)

#### What version of polars are you using?

`0.7.4`

#### What operating system are you using polars on?

Mac OSX 13.2.1 and Amazon Linux (AWS Lambda)

#### What node version are you using
node v16.19.1

#### Describe your bug.

The list of datatypes is incomplete. I see the python version has a binary type.

#### What are the steps to reproduce the behavior?

```js
import * as pl from 'nodejs-polars';

pl.Series('bytes', Uint8Array.from([]), pl.DataType.Binary) // Does not compile
```

#### What is the actual behavior?

`Uint8Array` is cast to `List(Uint8)` which is not the same in Parquet and Arrow. We're trying to read the Parquet files in Snowflake but the binary columns end up as empty objects as Snowflake is confused by this custom List type.

#### What is the expected behavior?

A `Binary` type that adheres to Arrow and Parquet specs.

**Comment by universalmind303** [comment]
yes I agree this should be supported. 

node polars is a bit behind the python implementation now, and it does not yet have the`Binary` dtype.

**Comment by Bidek56** [comment]
@flow-danny This code compiles in 0.8.1, can you please try it? Thx

**Comment by Bidek56** [comment]
This code works fine in 0.8.2, please re-open is this still an issue. Thx
```
import pl from 'nodejs-polars';
pl.Series('bytes', Uint8Array.from([]), pl.DataType.Binary);
```
