### ISSUE TITLE
An issue of running polar-rs

### ISSUE THREAD

**Issue by haziq-danial** [pola-rs/nodejs-polars#75]
#### Have you tried latest version of polars?

- [yes]

#### What version of polars are you using?

^0.7.4

#### What operating system are you using polars on?

Windows 11

#### What node version are you using
v18.8.0

#### Describe your bug.

Cannot run the library due to esbuild

#### What is the actual behavior?
```
No loader is configured for ".node" files: node_modules/nodejs-polars-win32-x64-msvc/nodejs-polars.win32-x64-msvc.node

    node_modules/nodejs-polars/bin/native-polars.js:68:48:
      68 │                         nativeBinding = require('nodejs-polars-win32-x64-msvc');
```

Another point that I want to add that the project that im building is based on vite + react

**Comment by haziq-danial** [comment]
Another point that i want to add is that the project im building is from react + vite

**Comment by Bidek56** [comment]
1. Please create a [MWE](https://leanprover-community.github.io/mwe.html#:~:text=A%20minimal%20working%20example%20is,include%20unnecessary%20details%20(minimal).)
2. "nodejs-polars": "^0.7.4" works fine using Node 18.16.0
```
import pl from 'nodejs-polars';
const expected = pl.DataFrame({
    list: ["a", "b", "c"],
  });
console.log(expected);
```

**Comment by Bidek56** [comment]
@haziq-danial Is this still an issue? If not please close this ticket. Thx
