### ISSUE TITLE
Running `fold` to perform a row sum gives an error code `DateExpected`.

### ISSUE THREAD

**Issue by Dan-C-Reed** [pola-rs/nodejs-polars#79]
#### Have you tried latest version of polars?

- [yes]✓
- [no]

If the problem was resolved, please update polars. :)

#### What version of polars are you using?
0.7.4

#### What operating system are you using polars on?
macOS

#### What node version are you using
20.3.0

#### Describe your bug.

Running `fold` to perform a row sum gives an error code `DateExpected`.

#### What are the steps to reproduce the behavior?

```js
import('nodejs-polars').then(mod => {pl = mod})
df = pl.DataFrame({
    "a": [1, 2, 3],
    "b": [1, 2, 3],
    "c": [1, 2, 3]
});
df.fold((s1, s2) => s1.plus(s2))
```

#### What is the actual behavior?

```js
Uncaught Error
    at dtypeWrap (xxx/node_modules/nodejs-polars/bin/series/index.js:29:65)
    at Proxy.plus (xxx/node_modules/nodejs-polars/bin/series/index.js:428:20)
    at REPL3:1:24
    at xxx/node_modules/nodejs-polars/bin/dataframe.js:166:60
    at Array.reduce (<anonymous>)
    at Proxy.fold (xxx/node_modules/nodejs-polars/bin/dataframe.js:166:38) {
  code: 'DateExpected'
}
```

#### What is the expected behavior?

```js
Series: 'a' [f64]
[
    3
    6
    9
]
```

**Comment by Bidek56** [comment]
@universalmind303 
I believe this [line](https://github.com/pola-rs/nodejs-polars/blob/0875ae0ab1d564ae69176ca0dcb52423121178f2/polars/series/index.ts#L1050) should be:

`return _Series(pli[internalMethod](_Series(_s), ...args));`

but I try it, I get: `Failed to recover JsSeries type from napi value`
Any  ideas? Thx
