### ISSUE TITLE
Who decides what optional dependencies to install when installing nodejs-polars using `npm`?

### ISSUE THREAD

**Issue by Deekshithrathod** [pola-rs/nodejs-polars#81]
#### Please use StackOverflow 

Is your question related to syntax or how you could do something with the polars library?
Yes

If a question is not yet on stackoverflow, please create a new question and post the link here, so we are noted.
https://stackoverflow.com/questions/76635638/who-decides-what-optional-dependencies-to-install-when-installing-nodejs-polars

**Comment by Bidek56** [comment]
You are using M1 processor which is very new and not widely supported by most packages.
I would suggest:
1. Use another CPU other than M1 or M2
2. Submit a PR for this repo to create a release for M1. I am not sure that M1 release will work since many libraries do not support M1 or M2 or may never support it since it's such a niche product.

**Comment by Bidek56** [comment]
Release platforms are defined in the GHA [yaml](https://github.com/pola-rs/nodejs-polars/blob/main/.github/workflows/create-js-release.yaml) 
@universalmind303  attempted to add an ARM release but was unable to do so due to dependency [issue](https://github.com/simd-lite/simd-json/issues/263).

**Comment by universalmind303** [comment]
answered on SO. 

WRT supported architectures m1 & m2 should be fully supported. 

you can see the [dependencies](https://www.npmjs.com/package/nodejs-polars?activeTab=dependencies) for a full list of available binaries for the given version. 

0.8.0 supports the following
- [win32-x64-msvc](https://www.npmjs.com/package/nodejs-polars-win32-x64-msvc)
- [darwin-x64](https://www.npmjs.com/package/nodejs-polars-darwin-x64) _(intel mac)_
- [linux-x64-gnu](https://www.npmjs.com/package/nodejs-polars-linux-x64-gnu)
- [darwin-arm64](https://www.npmjs.com/package/nodejs-polars-darwin-arm64) _(m1 & m2 mac)_
- [linux-arm64-gnu](https://www.npmjs.com/package/nodejs-polars-linux-arm64-gnu)
- [linux-arm64-musl](https://www.npmjs.com/package/nodejs-polars-linux-arm64-musl)
- [android-arm64](https://www.npmjs.com/package/nodejs-polars-android-arm64)
- [win32-ia32-msvc](https://www.npmjs.com/package/nodejs-polars-win32-ia32-msvc)
- [linux-x64-musl](https://www.npmjs.com/package/nodejs-polars-linux-x64-musl)

**Comment by Deekshithrathod** [comment]
@universalmind303 @Bidek56 Thanks guys for answering my query. I shall close this now.
