### ISSUE TITLE
Can I user nodejs-polars also in the browser

### ISSUE THREAD

**Issue by OliverAndersRWE** [pola-rs/nodejs-polars#90]
Hi,

I would love to use the library also in the frontend, but receive module not found messages for "none" browser libs like fs, path and so on..

Is it possilbe to configure/import the library also into a web application and run it in the browser?

Kind Regards,
Oliver

**Comment by Bidek56** [comment]
You are probably going to run into some sort of browser security issue trying to execute this lib in a browser.
I would suggest using this lib in a server side API and interacting with it from a JS front end like React.

**Comment by OliverAndersRWE** [comment]
Thanks for the clarification...

**Comment by mungojam** [comment]
given that it's just wrangling data, what are the aspects that block it from working in the browser? I know things like file loading won't work the same, but general data wrangling should be ok right?
