### ISSUE TITLE
`to_datetime` function to convert strings to dates

### ISSUE THREAD

**Issue by kevinschaich** [pola-rs/nodejs-polars#93]
#### Describe your feature request

Convert a string column into a Datetime column, with the ability to supply a `format` argument and other options.

```typescript
export const to_datetime = (
        format: str,
        time_unit: TimeUnit | None = None,
        time_zone: str | None = None,
        strict: bool = True,
        exact: bool = True,
        cache: bool = True,
        utc: bool | None = None,
): Expr => {
        ...
}
```

Python/Rust API: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.to_datetime.html#polars-expr-str-to-datetime

Python Implementation: https://github.com/pola-rs/polars/blob/1313e59009edd1d6e6f85ef9be32c4706cc4d0b8/py-polars/polars/expr/string.py#L80-L159

I saw this function but I don't think this is an entrypoint/exposed in the public API:

https://github.com/pola-rs/nodejs-polars/blob/e6c1edb2d16da906ab2f41e8341dbe71f7e2708d/src/lazy/dsl.rs#L580

**Comment by universalmind303** [comment]
so we are slightly behind on mirroring the python apis. This method used to be called `strptime`. 

https://pola-rs.github.io/nodejs-polars/interfaces/StringNamespace.html#strptime

**Comment by Bidek56** [comment]
`py-polars` has both `strptime` and `to_datetime`, `nodeje-polars` has only `strptime`.  
Are you missing any parameters from `strptime`?
