### ISSUE TITLE
any/any_horizontal

### ISSUE THREAD

**Issue by TyberiusPrime** [pola-rs/nodejs-polars#95]
Hey there,

I'm trying to filter on multiple columns, any of which matching should satisfy my filter.
Expanding from one to multiple columns gave me the awesome error message
'This is ambiguous. Try to combine the predicates with the 'all_horizontal' or `any_horizontal' expression.'

Alas I can't find either any_horizontal, all_horizontal, or any for that matter in nodejs-polars.

How I would have expected this to work:
```
let filtered = uq.filter(
      pl.any_horizontal(
        pl.col(index_columns).cast(pl.Utf8).str.toLowerCase().str.contains(q),
      ),
    );
```

Is it not implemented (yet), or am I missing it in the docs?

**Comment by TyberiusPrime** [comment]
Workaround for now:
```
    var filter = pl.col(index_columns[0]).cast(pl.Utf8).str.toLowerCase().str
      .contains(q);
    for (var ii = 1; ii < index_columns.length; ii++) {
      filter = filter.or(
        pl.col(index_columns[ii]).cast(pl.Utf8).str.toLowerCase().str.contains(
          q,
        ),
      );
    }

```

**Comment by Icequeen3333** [comment]
Nope, neither of them exist in implementation in the Node version, but they are implemented in Rust. I can work on implementing it, or at least trying to, in a little bit.
