### ISSUE TITLE
Categorical support

### ISSUE THREAD

**Issue by TyberiusPrime** [pola-rs/nodejs-polars#96]
I"m having some issues with categoricals  'on the border':

- you can't convert them to json ("not yet implemented in src/conversion.rs:147),
- I can't cast all of them to string columns 'easily':
  ```filtered.select(pl.col(pl.Categorical).cast(pl.Utf8));``` get's me 'Failed to convert JavaScript value `Object {"DataType":"Categorical"}` into rust type `String`' (possibly, I'm holding this wrong)

and slightly related: with_columns seems to be missing?

Could you provide some insights, thank you!

**Comment by Bidek56** [comment]
[withColumns](https://github.com/pola-rs/nodejs-polars/blob/e6c1edb2d16da906ab2f41e8341dbe71f7e2708d/polars/dataframe.ts#L1681) exists
Please provide MRE so I can help you debug the issue above. Thx

**Comment by TyberiusPrime** [comment]
Of course.

So the first problem isn't the json conversion (sorry, it was late, it's rows):

```
let strSeries = pl.Series("foo", ["one","two", "one", "two", "three"]);
  let strDf = pl.DataFrame({"foo": strSeries});
  console.log('strDf', strDf.rows()); // works

  let catSeries = strSeries.cast(pl.Categorical);
  let catDf = pl.DataFrame({"foo": catSeries});
  console.log('catDf', catDf.rows()); // -> thread '<unnamed>' panicked at 'not yet implemented', src/conversion.rs:147:18
  
  ```
And the 2nd one is 
``` (same as above, minus the last line):
catDf.select(pl.col(pl.Categorical)); 
```
which get's 'Failed to convert JavaScript value `Object {"DataType":"Categorical"}` into rust type `String`'

**Comment by Bidek56** [comment]
Why do you think this is a supported syntax? `catDf.select(pl.col(pl.Categorical))`

**Comment by TyberiusPrime** [comment]
Because that does work in python: https://pola-rs.github.io/polars-book/user-guide/expressions/column_selections/#by-data-type

**Comment by Bidek56** [comment]
#97 Should resolve selection by data type
