### ISSUE TITLE
use npm which package instead of shelling out 

### ISSUE THREAD

**Issue by sigmaSd** [pola-rs/nodejs-polars#98]
I'm using deno with nodejs-polars, works great except of some minor bug

I like to check permissions when I use deno, so with nodejs-polars it looks like this
```
Permissions:
{
  read: [
    "/home/mrcool/.deno/bin/deno",
    "/usr/bin/ldd",
    "/home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.8.0/bin/nodejs-polars.linux-x64-gnu."... 4 more characters
  ],
  write: [],
  net: [],
  env: "all",
  run: [ "/bin/sh" ],
  ffi: [
    "/home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars-linux-x64-gnu/0.8.0/nodejs-polars.linu"... 14 more characters
  ]
}
```

It all seem reasonable except of `run: sh`, this is invoked because of https://github.com/pola-rs/nodejs-polars/blob/main/polars/native-polars.js#L14 shelling out to call `which`

I believe a better way is to use https://www.npmjs.com/package/which it seems to be a popular library with a total of one dependency

I think its a better change overall (small performance optimization, more robust since which can be not installed on the system, )

If this sound good I can make a PR

**Comment by universalmind303** [comment]
Everything in `native-polars.js` is autogenerated code from the [napi framework](https://github.com/napi-rs/napi-rs). I think this would be a better suggestion for them.

**Comment by sigmaSd** [comment]
napi-rs code has been updated to not use which, but it still uses nodes exec_sync which will shell out to sh, 

I 'll have to test the new beahviour and I'll discuss it there, thanks
